language: r
sudo: required

before_install:
  - sudo apt-add-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update -qq
  
apt_packages:
  - bitcoind

r_packages:
  - jsonlite
  - httr
  - qrcode
  - RSQLite
  - shiny
  - DT

r_github_packages:
  - Rdatatable/data.table

after_script:
  - cat $(find . -maxdepth 1 -name "*.Rcheck" -type d)/tests/tests.Rout
