language: r
sudo: required

apt_packages:
 - libqrencode-dev

before_script:
  - sudo apt-add-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update -qq
  - sudo apt-get install bitcoind -y
  - echo 'server=1' > ~/.bitcoin/bitcoin.conf
  - echo 'regtest=1' >> ~/.bitcoin/bitcoin.conf
  - echo 'rpcuser=bitcoinduser' >> ~/.bitcoin/bitcoin.conf
  - echo 'rpcpassword=userpassbitcoind' >> ~/.bitcoin/bitcoin.conf
  - bitcoind -daemon

r_packages:
 - jsonlite
 - httr
 - raster
 - RSQLite

r_github_packages:
 - Rdatatable/data.table
 - hrbrmstr/qrencoder@2ee1e8799d3257a711b8bfe8b6f43552956d76cb